# Page settings
baseurl = "/"
canonifyURLs = false
rssLink = ""
title = "BitSwipe"
languageCode = "en-us"

[params]
  # Meta
  author = ""
  description = "Dedicated to the study and implementation of blockchain technology."
  email = ""

  # Services section
  [params.services]
    enable = true

    [[params.services.item]]
      title = "Banking and finances"
      description = "Payments, capital markets, commercial finance, point-to-point transactions and more."
      icon = "fa fa-university"

    [[params.services.item]]
      title = "Internet of things"
      description = "BitSwipe ATM enables digital currency integration, identity management and automation of industrial processes."
      icon = "fa fa-connectdevelop"

    [[params.services.item]]
      title = "Business"
      description = "Logistics & asset management, supply chains, health, media, energy and more."
      icon = "fa fa-truck"

      [[params.services.item]]
      title = "Government"
      description = "Records management, identity management, voting, taxes, government transparency, legislation, compliance, regulation and more."
      icon = "fa fa-id-card"

  # About section
  [params.about]
    enable = true
    title = "Engineers"
    description = "Our team of experienced business, product and technology leaders."

    [[params.about.item]]
      name = "Uriel Herrera"
      position = "Business Intelligence"
      description = "Blockchain / IoT / Inteligencia Artificial. Creo fervientemente que la combinación de estas tecnologías puede sentar un antes y un después en la manera en que comprendemos el mundo."
      img = "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAqNAAAAJDQzYzVmYTlkLTFjZWYtNDIzMC05Yjg0LWJkNWU2MTZkZDA3Yw.jpg"
      alt = "Uriel Herrera"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Gabo Esquivel"
      position = "Fintech, Cloud, OSS"
      description = "Desarollador de software especializándose en la construcción de soluciones en para servicios financieros utilizando computación en la nube, arquitecturas serverless y código abierto."
      img = "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAdKAAAAJDNlMGJhZWZhLTFjZDUtNDY0ZC1iNmUzLWEwMDMwZWEzYTY1Yw.jpg"
      alt = "Gabo Esquivel"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Walter Montes"
      position = "Desarrollo de Producto"
      description = "Pasó de la ingeniería y el liderazgo de los equipos de software al diseño centrado en el usuario de soluciones tecnológicas en torno a cloud, inteligencia artificial y plataformas abiertas."
      img = "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAsGAAAAJGQ4MGRlODM4LTk0NzQtNDJiYS1iYjlkLTBhMzNmMzk3MGJiYw.jpg"
      alt = "Walter Montes"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]

  # Contact section
  [params.contact]
    enable = true
    title = "CONTACT US"
    description = "We are very interested in hearing your ideas, questions and comments. We leave a message and we will respond as soon as possible."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "San José, Costa Rica"],
        # ["icon-phone", "6360-9999"],
        # ["icon-envelope", "info@blockchaincr.com"]
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; BitSwipe 2018 All Rights Reserved.'
